# Generated by Django 4.0.4 on 2022-05-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=150, verbose_name='Restaurant Name')),
                ('rest_desc', models.TextField(verbose_name='Description and Details')),
                ('food_type', models.CharField(choices=[(None, 'Select Type of Food'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Mexican/Spanish', 'Mexican/Spanish'), ('Japanese', 'Japanese'), ('American', 'American'), ('Thai', 'Thai'), ('Indian', 'Indian'), ('French', 'French'), ('Greek', 'Greek'), ('German', 'German'), ('British', 'British'), ('Other', 'Other')], default='None', max_length=15, verbose_name='Type of Food')),
                ('rest_url', models.URLField(blank=True, verbose_name='Website URL')),
                ('rest_phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('rest_logo', models.ImageField(upload_to='', verbose_name='Restaurant Logo')),
            ],
        ),
    ]
