# Generated by Django 4.0.4 on 2022-05-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matches',
            field=models.ManyToManyField(blank=True, to='dinr.restaurant'),
        ),
    ]
