# Generated by Django 4.0.4 on 2022-05-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_apt',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apartment Line'),
        ),
        migrations.AlterField(
            model_name='user',
            name='apt_loc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apartment Line'),
        ),
    ]
