# Generated by Django 4.0.4 on 2022-05-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinr', '0002_alter_user_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_logo',
            field=models.ImageField(upload_to='uploads/', verbose_name='Restaurant Logo'),
        ),
    ]
